69 add repositories tests
Win-ther/SpringbootGroupProject pull request #77
Opened 2024-04-05 18:23 UTC by Win-ther

### Related Issue(s)
Closes #69 

### Proposed Changes
- Add tests for UserRepository and MessageRepositort
- Removed Initializer for DB, made tests not funtion as they should.
- Refactored a method in UserRepository to fit with other methods.

### Description
Testing for repositories.

2024-04-06 06:09 UTC, Frlundsten requested changes
Great job! It is nice to finally have some tests 😄 I found a typo that would be nice to fix for clarity.

2024-04-06 06:09 UTC, vonfredd commented on src/test/java/se/iths/springbootgroupproject/repositories/MessageRepositoryTest.java
> +    }
I do not think this updates a user 😉

2024-04-06 11:06 UTC, Win-ther commented on src/test/java/se/iths/springbootgroupproject/repositories/MessageRepositoryTest.java
> +    }
Fixed^^

2024-04-06 18:24 UTC, marcusju23 commented
> ## [![Quality Gate Failed](https://camo.githubusercontent.com/5333b8e2ff49bd5efdc6d2efd30ec08d7ac8d67c5e80190d03b6c2cb29a5de8b/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d6661696c65642d323070782e706e67)](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=77) **Quality Gate failed**
> 
> Failed conditions ![](https://camo.githubusercontent.com/ee78c91cde137cf4668f72b8e1247dadaaeb117c99c74bed0f21b1681b517491/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=77&metric=new_coverage&view=list) (required ≥ 80%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=77)

@Win-ther 0.0% coverage due to integrated tests? Perhaps an adjustment in the pipeline configuration and dependencies could resolve this? 🤔 But that's for another issue if needed 😄

2024-04-06 18:25 UTC, marcusju23 approved these changes
Good stuff! 🙌 Just one thing.

> ## [![Quality Gate Failed](https://camo.githubusercontent.com/5333b8e2ff49bd5efdc6d2efd30ec08d7ac8d67c5e80190d03b6c2cb29a5de8b/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d6661696c65642d323070782e706e67)](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=77) **Quality Gate failed**
> 
> Failed conditions ![](https://camo.githubusercontent.com/ee78c91cde137cf4668f72b8e1247dadaaeb117c99c74bed0f21b1681b517491/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=77&metric=new_coverage&view=list) (required ≥ 80%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=77)

@Win-ther 0.0% coverage due to integrated tests? Perhaps an adjustment in the pipeline configuration and dependencies could resolve this? 🤔 But that's for another issue if needed 😄

2024-04-06 20:37 UTC, Win-ther commented
> Good stuff! 🙌 Just one thing.
> 
> > ## [![Quality Gate Failed](https://camo.githubusercontent.com/5333b8e2ff49bd5efdc6d2efd30ec08d7ac8d67c5e80190d03b6c2cb29a5de8b/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d6661696c65642d323070782e706e67)](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=77) **Quality Gate failed**
> > Failed conditions ![](https://camo.githubusercontent.com/ee78c91cde137cf4668f72b8e1247dadaaeb117c99c74bed0f21b1681b517491/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [0.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=Win-ther_SpringbootGroupProject&pullRequest=77&metric=new_coverage&view=list) (required ≥ 80%)
> > [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=Win-ther_SpringbootGroupProject&pullRequest=77)
> 
> @Win-ther 0.0% coverage due to integrated tests? Perhaps an adjustment in the pipeline configuration and dependencies could resolve this? 🤔 But that's for another [issue](https://github.com/Win-ther/SpringbootGroupProject/issues/80) if needed 😄

The quality-gate failing with 0.0% coverage on new code is because I added code to the service class. If you click on the failed analysis you can see that it only mentions UserService.
![image](https://github.com/Win-ther/SpringbootGroupProject/assets/143023413/7b8f0547-a7ac-45c1-ab16-12e8bd629459)
The analsysis seems to not care about the Repositories, even in PR #3 the analysis does not react to the repositories.

It doesn't react to the Integration tests, because they do not add coverage, and the coverage is 100% by default for the repositories since they don't have real methods. They are interfaces.
Because of that I see no reason to add an Issue(#80) for it since there is nothing to fix. Or am I missing something? 🙂

2024-04-06 22:34 UTC, marcusju23 commented
> The quality-gate failing with 0.0% coverage on new code is because I added code to the service class. If you click on the failed analysis you can see that it only mentions UserService. ![image](https://private-user-images.githubusercontent.com/143023413/320232759-7b8f0547-a7ac-45c1-ab16-12e8bd629459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NDI1ODUsIm5iZiI6MTcxMjQ0MjI4NSwicGF0aCI6Ii8xNDMwMjM0MTMvMzIwMjMyNzU5LTdiOGYwNTQ3LWE3YWMtNDVjMS1hYjE2LTEyZThiZDYyOTQ1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNlQyMjI0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTVlYTllY2ZhM2E4YTgxMDE5ZTYyZjk3NzkxYTYwMzA0NjkxZTMyNjczODk4MDZhMTFhMmNmOTQ3YWNmYmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6BGT5Ufrc2PFUfCpAE5iBPHjzD8twG5u8wTKnK7kktk) The analsysis seems to not care about the Repositories, even in PR #3 the analysis does not react to the repositories.

Ah okay, I somehow missed that. I'll close #80

2024-04-07 16:50 UTC, vonfredd approved these changes
Thank you for your service, 10/10

2024-04-08 12:31 UTC, altmannk approved these changes
LGTM 👍🏽

2024-04-08 12:31 UTC, merged